run

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,18 +1,29 @@
 FROM node:13.12.0-alpine as build
 
+# Создаем группу и пользователя для безопасности
+RUN addgroup -S appgroup && adduser -S appuser -G appgroup
+
+# Устанавливаем домашний каталог для нашего приложения
 WORKDIR /app
 
-# Копирование файлов package.json и package-lock.json (если он есть)
+# Используем созданного пользователя
+USER appuser
+
+# Копируем файлы package.json и package-lock.json (если он есть)
 COPY package*.json ./
 
-# Установка всех зависимостей, включая react и react-dom
+# Устанавливаем все зависимости, включая react и react-dom
 RUN npm install
 
-# Копирование остальных файлов
+# Копируем остальные файлы
 COPY . .
 
-# Сборка проекта
+# Собираем проект
 RUN npm run build
 
+# Здоровье контейнера проверяется путем проверки доступности HTTP сервера
+# HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1
+
 # Команда для копирования результата сборки
-CMD cp -r build result_build
+CMD ["cp", "-r", "build", "result_build"]
+
